[package]
name = "lm-sanaga"
version = "0.1.0"
edition = "2024"

[features]
#dhat-heap = []

[dependencies]
sn_inference = { path = "../sn_inference" }
sn_core = { path = "../sn_core" }

axum = { version = "0.8.4", features = ["macros"] }
log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tower = "0.5.2"
http = "1.3.1"
futures-util = "0.3.31"