[package]
name = "lm-sanaga"
version = "0.1.0"
edition = "2024"

[dependencies]
mlx-rs = "0.25.1"
mlx-sys = "0.2.0"
serde_json="1.0.140"
serde = { version = "1.0.219", features = ["derive", "rc"] }
walkdir ="2.5.0"
log="0.4.27"
env_logger = "0.11.8"
glob="0.3.2"
minijinja="2.11.0"
tokenizers = "0.21.4-dev.0"
hex = "0.4.3"
thiserror="2.0.12"
itertools = "0.14.0"
rayon = "1.10.0"
#tokio = { version = "1.46.1", features = ["full"]  }
crossbeam = "0.8.4"
